<?php  
if(function_exists('acf_add_local_field_group')):

acf_add_local_field_group(array(
	'key' => 'group_5c0d13ab5e2c6',
	'title' => 'Booking',
	'fields' => array(
		array(
			'key' => 'field_5c1a4f8a99447',
			'label' => 'Select which Calendar',
			'name' => 'calendar-define',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'null' => 'Loading..'
			),
			'default_value' => array(
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_5c1cf5a696803',
			'label' => 'Booking day',
			'name' => 'booking_day',
			'type' => 'date_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'display_format' => 'd.m.Y',
			'return_format' => 'd.m.Y',
			'first_day' => 1,
		),
		array(
			'key' => 'field_5c1cf5c796804',
			'label' => 'Booking type',
			'name' => 'booking_type',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'full' => 'Full Day',
				'first' => 'First Half',
				'last' => 'Last Half',
			),
			'default_value' => array(
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_5c14c24642415',
			'label' => 'Location',
			'name' => 'location',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5c14c45f42426',
			'label' => 'Form Fields',
			'name' => 'form_fields',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5c0d2f727e57i',
			'label' => 'Booked off',
			'name' => 'booked',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'med-booking',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_5c0d13999b18d',
	'title' => 'Calendar',
	'fields' => array(
		array(
			'key' => 'field_5c0d2f727e57d',
			'label' => 'Shortcode',
			'name' => 'shortcode',
			'type' => 'text',
			'instructions' => 'Paste this shortcode onto a post/page to run this calendar.',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '100%',
				'class' => '',
				'id' => 'calendar-shortcode',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 1
		),
		array(
			'key' => 'field_5c0d2dee956fv',
			'label' => 'Full Day Mediation - Start Time',
			'name' => 'time_start0',
			'type' => 'text',
			'instructions' => 'Time your first booking starts.',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => 'timepicker',
				'id' => '',
			),
		),
		array(
			'key' => 'field_5c1f9bb92fbdh',
			'label' => 'Full Day Mediation - End Time',
			'name' => 'time_end0',
			'type' => 'text',
			'instructions' => 'Time your first booking ends.',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => 'timepicker',
				'id' => '',
			),
		),
		array(
			'key' => 'field_5c0d2dee956f0',
			'label' => 'Morning Mediation - Start Time',
			'name' => 'time_start1',
			'type' => 'text',
			'instructions' => 'Time your first booking starts.',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => 'timepicker',
				'id' => '',
			),
		),
		array(
			'key' => 'field_5c1f9bb92fbd0',
			'label' => 'Morning Mediation - End Time',
			'name' => 'time_end1',
			'type' => 'text',
			'instructions' => 'Time your first booking ends.',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => 'timepicker',
				'id' => '',
			),
		),
		array(
			'key' => 'field_5c1f9abff221c',
			'label' => 'Afternoon Mediation – Start Time',
			'name' => 'time_start2',
			'type' => 'text',
			'instructions' => 'Time your second booking starts.',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => 'timepicker',
				'id' => '',
			),
		),
		array(
			'key' => 'field_5c1f9c31b36c9',
			'label' => 'Afternoon Mediation – End Time',
			'name' => 'time_end2',
			'type' => 'text',
			'instructions' => 'Time your second booking ends.',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => 'timepicker bk-breakline-acf',
				'id' => '',
			),
		),
		array(
			'key' => 'field_5c1f9c31b36cr',
			'label' => 'Add Locations',
			'name' => 'location1',
			'type' => 'text',
			'instructions' => 'Add up to 6 mediation appointment locations in the fields below.',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '33.3333',
				'class' => 'med-booking-row1',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'Add location',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5c1f9c31b36ce',
			'label' => 'Add Locations',
			'name' => 'location2',
			'type' => 'text',
			'instructions' => 'Add up to 6 mediation appointment locations in the fields below.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '33.3333',
				'class' => 'med-booking-row1 hide-loc-titles',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'Add location',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5c1f9c31b36cz',
			'label' => 'Add Locations',
			'name' => 'location3',
			'type' => 'text',
			'instructions' => 'Add up to 6 mediation appointment locations in the fields below.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '33.3333',
				'class' => 'med-booking-row1 hide-loc-titles',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'Add location',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5c1f9c31b36ca',
			'label' => 'Add Locations',
			'name' => 'location4',
			'type' => 'text',
			'instructions' => 'Add up to 6 mediation appointment locations in the fields below.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '33.3333',
				'class' => 'med-booking-row1 gone-loc-titles',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'Add location',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5c1f9c31b36cb',
			'label' => 'Add Locations',
			'name' => 'location5',
			'type' => 'text',
			'instructions' => 'Add up to 6 mediation appointment locations in the fields below.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '33.3333',
				'class' => 'med-booking-row1 gone-loc-titles',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'Add location',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5c1f9c31b36ci',
			'label' => 'Add Locations',
			'name' => 'location6',
			'type' => 'text',
			'instructions' => 'Add up to 6 mediation appointment locations in the fields below.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '33.3333',
				'class' => 'med-booking-row1 gone-loc-titles',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'Add location',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5c1f9c31b36ct',
			'label' => 'Administrator Email Address',
			'name' => 'email',
			'type' => 'email',
			'instructions' => 'This email will receive appointment booking details for this calendar',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '33.3333',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'Add email',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5c1f9c31b36cs',
			'label' => 'Name of Mediator',
			'name' => 'text',
			'type' => 'text',
			'instructions' => 'Add a name for this mediator',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '33.3333',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'Add mediator name',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5c1f9c31b36co',
			'label' => 'Booking Month range',
			'name' => 'bookingrange',
			'type' => 'number',
			'instructions' => 'Set the maximum number of months with visible availability',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '33.3333',
				'class' => '',
				'id' => '',
			),
			'default_value' => 12,
			'placeholder' => 'Add booking month range',
			'prepend' => '',
			'append' => '',
			'min' => 3,
			'max' => 24,
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'med-calendar',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

endif;